CLASS_STATUS_ACTIVE = "Activa"
CLASS_STATUS_CANCELLED = "Cancelada"
CLASS_STATUSES = (CLASS_STATUS_ACTIVE, CLASS_STATUS_CANCELLED)

ENROLLMENT_TYPE_SINGLE = "Suelta"
ENROLLMENT_TYPE_MONTHLY = "Mensual"
ENROLLMENT_TYPES = (ENROLLMENT_TYPE_SINGLE, ENROLLMENT_TYPE_MONTHLY)

ENROLLMENT_STATUS_PENDING_PAYMENT = "pending_payment"
ENROLLMENT_STATUS_PAID = "paid"
ENROLLMENT_STATUS_EXPIRED = "expired"
ENROLLMENT_STATUS_CANCELLED = "cancelled"
ENROLLMENT_STATUSES = (
    ENROLLMENT_STATUS_PENDING_PAYMENT,
    ENROLLMENT_STATUS_PAID,
    ENROLLMENT_STATUS_EXPIRED,
    ENROLLMENT_STATUS_CANCELLED,
)
ENROLLMENT_PAYABLE_STATUSES = (ENROLLMENT_STATUS_PENDING_PAYMENT,)
ENROLLMENT_CAPACITY_STATUSES = (
    ENROLLMENT_STATUS_PENDING_PAYMENT,
    ENROLLMENT_STATUS_PAID,
)
ENROLLMENT_REOPENABLE_STATUSES = (
    ENROLLMENT_STATUS_EXPIRED,
    ENROLLMENT_STATUS_CANCELLED,
)

PAYMENT_TYPE_MONTHLY_SUBSCRIPTION = "monthly_subscription"
PAYMENT_TYPE_INDIVIDUAL_CLASS = "individual_class"
PAYMENT_TYPES = (
    PAYMENT_TYPE_MONTHLY_SUBSCRIPTION,
    PAYMENT_TYPE_INDIVIDUAL_CLASS,
)

PAYMENT_METHOD_MERCADO_PAGO = "mercado_pago"
PAYMENT_METHOD_CARD = "card"
PAYMENT_METHOD_CREDIT = "credit"
PAYMENT_METHODS = (
    PAYMENT_METHOD_MERCADO_PAGO,
    PAYMENT_METHOD_CARD,
    PAYMENT_METHOD_CREDIT,
)

PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_APPROVED = "approved"
PAYMENT_STATUS_REJECTED = "rejected"
PAYMENT_STATUS_EXPIRED = "expired"
PAYMENT_STATUSES = (
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_APPROVED,
    PAYMENT_STATUS_REJECTED,
    PAYMENT_STATUS_EXPIRED,
)

CREDIT_STATUS_AVAILABLE = "Disponible"
CREDIT_STATUS_USED = "Usado"
CREDIT_API_STATUS_AVAILABLE = "available"
CREDIT_API_STATUS_USED = "used"
CREDIT_API_STATUS_EXPIRED = "expired"
CREDIT_EXPIRATION_DAYS = 30

NOTIFICATION_STATUS_UNREAD = "unread"
NOTIFICATION_STATUS_READ = "read"

DISCOUNT_PERCENTAGES = (0, 40, 70)
DISCOUNT_PERIODS = (
    {"percentage": 0, "start_day": 1, "end_day": 14},
    {"percentage": 40, "start_day": 15, "end_day": 21},
    {"percentage": 70, "start_day": 22, "end_day": None},
)

PAYMENT_OPTION_FULL = "full"
PAYMENT_OPTION_DEPOSIT = "deposit"

PAYMENT_RETURN_STATUS_SUCCESS = "success"
PAYMENT_RETURN_STATUS_FAILURE = "failure"
PAYMENT_RETURN_STATUS_PENDING = "pending"

MERCADO_PAGO_STATUS_APPROVED = "approved"
MERCADO_PAGO_STATUS_PENDING = "pending"
MERCADO_PAGO_STATUS_IN_PROCESS = "in_process"
